# log
ts_diff: 0

# map
min_corner_angle: 80
enable_draw_corners: True

# particle
stride_sd: 30

# turtle
max_turtle_heading_hist_len: 10

# map matching
begin: "2021-11-26 14:38:05"
end: "2021-11-26 14:47:06"

enable_draw_nodes: False
enable_draw_links: False
max_link_len: 80
set_links_policy: 3
nodes_show_policy: 2

particle_num: 256
init_pos: [1150, 955]
init_pos_sd: 16
init_direct: 270
init_direct_sd: 45
rand_pos_range: 512
match_weight_policy: 3
estim_pos_policy: 1

# pdr
file_range_policy: 1
log_file: 2021-11-26_.pkl

pdr_win_size: 0.1

step_len_coef: 0.42
stature: 1.7
default_speed: 1

step_begin_acc_thresh: 1.05
pos_peak_acc_thresh: 1.11
neg_peak_acc_thresh: 0.93
step_end_acc_thresh: 0.97
min_step_interval: 0.5
max_status_interval: 0.5
max_step_interval: 2

rotate_ax: 4
gyro_drift: 0

# particle filter
enable_truth: False

map_img_file: ptokai3.pgm
map_conf_file: ptokai3.yaml
enable_draw_beacons: False
enable_clear_map: True
map_show_policy: 3

enable_save_video: False
enable_save_img: False
file_name:
frame_rate: 1

win_stride: 1
win_size: 4
win_policy: 1

direct_sd: 30
max_particle_stride: 32
lost_resample_policy: 1

propag_coef: 4
el_correction: 2
dist_sd: 64